# Generated by Django 5.2.12 on 2026-04-15 07:51

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
import django.contrib.postgres.search
import django.db.models.deletion
import django_lifecycle.mixins
import pulpcore.app.models.base
import pulpcore.app.models.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("ansible", "0001_initial_squashed_0040_ansiblerepository_keyring"),
        ("ansible", "0041_alter_collectionversion_collection"),
        ("ansible", "0042_ansiblerepository_gpgkey"),
        ("ansible", "0043_alter_collectionversionsignature_data"),
        ("ansible", "0044_alter_collectionremote_token"),
        ("ansible", "0045_downloadlog"),
        ("ansible", "0046_add_fulltext_search_fix"),
        ("ansible", "0047_ansible_namespace"),
        ("ansible", "0048_collectionversionmark"),
        ("ansible", "0049_rbac_permissions"),
        ("ansible", "0050_crossrepositorycollectionversionindex"),
        ("ansible", "0051_cvindex_build"),
        ("ansible", "0052_alter_ansiblecollectiondeprecated_content_ptr_and_more"),
        ("ansible", "0053_collectiondownloadcount"),
        ("ansible", "0054_split_collection_version_numbers"),
    ]

    initial = True

    dependencies = [
        ("core", "0106_alter_artifactdistribution_distribution_ptr_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "pulp_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("pulp_created", models.DateTimeField(auto_now_add=True)),
                ("pulp_last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("namespace", models.CharField(editable=False, max_length=64)),
                ("name", models.CharField(editable=False, max_length=64)),
            ],
            options={
                "unique_together": {("namespace", "name")},
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "pulp_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("pulp_created", models.DateTimeField(auto_now_add=True)),
                ("pulp_last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(editable=False, max_length=64, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "content_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="ansible_role",
                        serialize=False,
                        to="core.content",
                    ),
                ),
                ("namespace", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=64)),
                ("version", models.CharField(max_length=128)),
            ],
            options={
                "unique_together": {("version", "name", "namespace")},
                "default_related_name": "%(app_label)s_%(model_name)s",
            },
            bases=("core.content",),
        ),
        migrations.CreateModel(
            name="CollectionImport",
            fields=[
                ("messages", models.JSONField(default=list, editable=False)),
                (
                    "task",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="core.task",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "ordering": ["task__pulp_created"],
            },
        ),
        migrations.CreateModel(
            name="RoleRemote",
            fields=[
                (
                    "remote_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="ansible_roleremote",
                        serialize=False,
                        to="core.remote",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_related_name": "%(app_label)s_%(model_name)s",
            },
            bases=("core.remote",),
        ),
        migrations.CreateModel(
            name="AnsibleRepository",
            fields=[
                (
                    "repository_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="ansible_ansiblerepository",
                        serialize=False,
                        to="core.repository",
                    ),
                ),
                ("last_synced_metadata_time", models.DateTimeField(null=True)),
                (
                    "keyring",
                    models.FilePathField(blank=True, path="/etc/pulp/certs/", recursive=True),
                ),
            ],
            options={
                "default_related_name": "%(app_label)s_%(model_name)s",
                "permissions": (
                    ("modify_ansible_repo_content", "Can modify ansible repository content"),
                ),
            },
            bases=("core.repository",),
        ),
        migrations.CreateModel(
            name="collectionversion",
            fields=[
                (
                    "content_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="ansible_collectionversion",
                        serialize=False,
                        to="core.content",
                    ),
                ),
                ("version", models.CharField(editable=False, max_length=128)),
                ("contents", models.JSONField(default=list, editable=False)),
                (
                    "collection",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="ansible.collection",
                        to_field="pulp_id",
                    ),
                ),
                (
                    "authors",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=64),
                        default=list,
                        editable=False,
                        size=None,
                    ),
                ),
                ("dependencies", models.JSONField(default=dict, editable=False)),
                ("description", models.TextField(blank=True, default="", editable=False)),
                ("docs_blob", models.JSONField(default=dict, editable=False)),
                (
                    "documentation",
                    models.CharField(blank=True, default="", editable=False, max_length=2000),
                ),
                (
                    "homepage",
                    models.CharField(blank=True, default="", editable=False, max_length=2000),
                ),
                (
                    "issues",
                    models.CharField(blank=True, default="", editable=False, max_length=2000),
                ),
                (
                    "license",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=32),
                        default=list,
                        editable=False,
                        size=None,
                    ),
                ),
                ("name", models.CharField(editable=False, max_length=64)),
                ("namespace", models.CharField(editable=False, max_length=64)),
                (
                    "repository",
                    models.CharField(blank=True, default="", editable=False, max_length=2000),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        editable=False, related_name="ansible_collectionversion", to="ansible.tag"
                    ),
                ),
                ("search_vector", django.contrib.postgres.search.SearchVectorField(default="")),
                ("is_highest", models.BooleanField(default=False, editable=False)),
                ("files", models.JSONField(default=dict, editable=False)),
                ("manifest", models.JSONField(default=dict, editable=False)),
                ("requires_ansible", models.CharField(max_length=255, null=True)),
            ],
            options={
                "default_related_name": "%(app_label)s_%(model_name)s",
                "unique_together": {("namespace", "name", "version")},
            },
            bases=("core.content",),
        ),
        migrations.CreateModel(
            name="AnsibleDistribution",
            fields=[
                (
                    "distribution_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="ansible_ansibledistribution",
                        serialize=False,
                        to="core.distribution",
                    ),
                ),
            ],
            options={
                "default_related_name": "%(app_label)s_%(model_name)s",
            },
            bases=("core.distribution",),
        ),
        migrations.CreateModel(
            name="AnsibleCollectionDeprecated",
            fields=[
                (
                    "content_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="ansible_ansiblecollectiondeprecated",
                        serialize=False,
                        to="core.content",
                    ),
                ),
                ("namespace", models.CharField(editable=False, max_length=64)),
                ("name", models.CharField(editable=False, max_length=64)),
            ],
            options={
                "default_related_name": "%(app_label)s_%(model_name)s",
                "unique_together": {("namespace", "name")},
            },
            bases=("core.content",),
        ),
        migrations.CreateModel(
            name="GitRemote",
            fields=[
                (
                    "remote_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="ansible_gitremote",
                        serialize=False,
                        to="core.remote",
                    ),
                ),
                ("metadata_only", models.BooleanField(default=False)),
                ("git_ref", models.TextField()),
            ],
            options={
                "default_related_name": "%(app_label)s_%(model_name)s",
            },
            bases=("core.remote",),
        ),
        migrations.CreateModel(
            name="CollectionRemote",
            fields=[
                (
                    "remote_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="ansible_collectionremote",
                        serialize=False,
                        to="core.remote",
                    ),
                ),
                ("requirements_file", models.TextField(null=True)),
                ("auth_url", models.CharField(max_length=255, null=True)),
                ("token", models.TextField(max_length=2000, null=True)),
                ("sync_dependencies", models.BooleanField(default=True)),
                ("signed_only", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
                "default_related_name": "%(app_label)s_%(model_name)s",
            },
            bases=("core.remote",),
        ),
        migrations.CreateModel(
            name="CollectionVersionSignature",
            fields=[
                (
                    "content_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="ansible_collectionversionsignature",
                        serialize=False,
                        to="core.content",
                    ),
                ),
                ("data", models.BinaryField()),
                ("digest", models.CharField(max_length=64)),
                ("pubkey_fingerprint", models.CharField(max_length=64)),
                (
                    "signed_collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signatures",
                        to="ansible.collectionversion",
                    ),
                ),
                (
                    "signing_service",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signatures",
                        to="core.signingservice",
                    ),
                ),
            ],
            options={
                "default_related_name": "%(app_label)s_%(model_name)s",
                "unique_together": {("pubkey_fingerprint", "signed_collection")},
            },
            bases=("core.content",),
        ),
        migrations.AddConstraint(
            model_name="collectionversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_highest", True)),
                fields=("collection", "is_highest"),
                name="unique_is_highest",
            ),
        ),
        migrations.RunSQL(
            sql="\nUPDATE ansible_collectionversion AS c\nSET search_vector = (\n    SELECT \n    setweight(to_tsvector(coalesce(namespace,'')), 'A')\n    || setweight(to_tsvector(coalesce(name, '')), 'A')\n    || (\n      SELECT\n        setweight(to_tsvector(\n          coalesce(string_agg(\"ansible_tag\".\"name\", ' '), '')\n        ), 'B')\n      FROM\n        \"ansible_tag\" INNER JOIN \"ansible_collectionversion_tags\" ON (\"ansible_tag\".\"pulp_id\" = \"ansible_collectionversion_tags\".\"tag_id\")\n    )\n    || (\n      SELECT\n        setweight(to_tsvector(\n          coalesce(string_agg(cvc ->> 'name', ' '), '')\n        ), 'C')\n      FROM jsonb_array_elements(cv.contents) AS cvc\n    )\n    || setweight(to_tsvector(coalesce(description, '')), 'D')\n\n    FROM ansible_collectionversion cv\n    WHERE c.content_ptr_id = cv.content_ptr_id\n)\n",
            reverse_sql="",
        ),
        migrations.RunSQL(
            sql="\nCREATE OR REPLACE FUNCTION update_collection_ts_vector()\n    RETURNS TRIGGER AS\n$$\nBEGIN\n    NEW.search_vector := (\n        SELECT \n    setweight(to_tsvector(coalesce(namespace,'')), 'A')\n    || setweight(to_tsvector(coalesce(name, '')), 'A')\n    || (\n      SELECT\n        setweight(to_tsvector(\n          coalesce(string_agg(\"ansible_tag\".\"name\", ' '), '')\n        ), 'B')\n      FROM\n        \"ansible_tag\" INNER JOIN \"ansible_collectionversion_tags\" ON (\"ansible_tag\".\"pulp_id\" = \"ansible_collectionversion_tags\".\"tag_id\")\n    )\n    || (\n      SELECT\n        setweight(to_tsvector(\n          coalesce(string_agg(cvc ->> 'name', ' '), '')\n        ), 'C')\n      FROM jsonb_array_elements(cv.contents) AS cvc\n    )\n    || setweight(to_tsvector(coalesce(description, '')), 'D')\n\n        FROM ansible_collectionversion cv\n        WHERE cv.content_ptr_id = NEW.content_ptr_id\n    );\n    RETURN NEW;\nEND;\n$$ LANGUAGE plpgsql;\nCREATE TRIGGER update_ts_vector\n    BEFORE UPDATE\n    ON ansible_collectionversion\n    FOR EACH ROW\nEXECUTE PROCEDURE update_collection_ts_vector();\n",
            reverse_sql="\nDROP TRIGGER IF EXISTS update_ts_vector ON ansible_collectionversion;\nDROP FUNCTION IF EXISTS update_collection_ts_vector();\n",
        ),
        migrations.RemoveField(
            model_name="ansiblerepository",
            name="keyring",
        ),
        migrations.AddField(
            model_name="ansiblerepository",
            name="gpgkey",
            field=models.TextField(null=True),
        ),
        migrations.RemoveField(
            model_name="collectionversionsignature",
            name="data",
        ),
        migrations.AddField(
            model_name="collectionversionsignature",
            name="data",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="collectionversion",
            name="collection",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="versions",
                to="ansible.collection",
            ),
        ),
        migrations.RemoveField(
            model_name="collectionremote",
            name="token",
        ),
        migrations.AddField(
            model_name="collectionremote",
            name="token",
            field=pulpcore.app.models.fields.EncryptedTextField(null=True),
        ),
        migrations.CreateModel(
            name="DownloadLog",
            fields=[
                (
                    "pulp_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("pulp_created", models.DateTimeField(auto_now_add=True)),
                ("pulp_last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("ip", models.GenericIPAddressField()),
                ("extra_data", models.JSONField(null=True)),
                ("user_agent", models.TextField()),
                (
                    "content_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="download_logs",
                        to="core.content",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="download_logs",
                        to="core.repository",
                    ),
                ),
                (
                    "repository_version",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="download_logs",
                        to="core.repositoryversion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="download_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.RunSQL(
            sql="\nCREATE OR REPLACE FUNCTION update_collection_ts_vector()\n    RETURNS TRIGGER AS\n$$\nBEGIN\n    NEW.search_vector := (\n        SELECT \n    setweight(to_tsvector(coalesce(namespace,'')), 'A')\n    || setweight(to_tsvector(coalesce(name, '')), 'A')\n    || (\n      SELECT\n        setweight(to_tsvector(\n          coalesce(string_agg(\"ansible_tag\".\"name\", ' '), '')\n        ), 'B')\n      FROM\n        \"ansible_tag\" INNER JOIN \"ansible_collectionversion_tags\"\n        ON\n        (\"ansible_tag\".\"pulp_id\" = \"ansible_collectionversion_tags\".\"tag_id\" )\n      WHERE\n        \"ansible_collectionversion_tags\".\"collectionversion_id\" = cv.content_ptr_id\n    )\n    || (\n      SELECT\n        setweight(to_tsvector(\n          coalesce(string_agg(cvc ->> 'name', ' '), '')\n        ), 'C')\n      FROM jsonb_array_elements(cv.contents) AS cvc\n    )\n    || setweight(to_tsvector(coalesce(description, '')), 'D')\n\n        FROM ansible_collectionversion cv\n        WHERE cv.content_ptr_id = NEW.content_ptr_id\n    );\n    RETURN NEW;\nEND;\n$$ LANGUAGE plpgsql;\nDROP TRIGGER IF EXISTS update_ts_vector ON ansible_collectionversion;\nCREATE TRIGGER update_ts_vector\n    BEFORE UPDATE\n    ON ansible_collectionversion\n    FOR EACH ROW\nEXECUTE PROCEDURE update_collection_ts_vector();\n",
            reverse_sql="\nDROP TRIGGER IF EXISTS update_ts_vector ON ansible_collectionversion;\nDROP FUNCTION IF EXISTS update_collection_ts_vector();\n",
        ),
        migrations.RunSQL(
            sql="\nUPDATE ansible_collectionversion SET is_highest = False where is_highest = False;\nUPDATE ansible_collectionversion SET is_highest = True where is_highest = True;\n",
            reverse_sql="",
        ),
        migrations.CreateModel(
            name="AnsibleNamespace",
            fields=[
                (
                    "pulp_id",
                    models.UUIDField(
                        default=pulpcore.app.models.base.pulp_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("pulp_created", models.DateTimeField(auto_now_add=True)),
                ("pulp_last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=64, unique=True)),
            ],
            options={
                "abstract": False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="AnsibleNamespaceMetadata",
            fields=[
                (
                    "content_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.content",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("company", models.CharField(blank=True, default="", max_length=64)),
                ("email", models.CharField(blank=True, default="", max_length=256)),
                ("description", models.CharField(blank=True, default="", max_length=256)),
                ("resources", models.TextField(blank=True, default="")),
                ("links", django.contrib.postgres.fields.hstore.HStoreField(default=dict)),
                ("avatar_sha256", models.CharField(max_length=64, null=True)),
                ("metadata_sha256", models.CharField(db_index=True, max_length=64)),
                (
                    "namespace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="metadatas",
                        to="ansible.ansiblenamespace",
                    ),
                ),
            ],
            options={
                "default_related_name": "%(app_label)s_%(model_name)s",
                "unique_together": {("metadata_sha256",)},
            },
            bases=("core.content",),
        ),
        migrations.AddField(
            model_name="ansiblerepository",
            name="private",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelOptions(
            name="ansibledistribution",
            options={
                "default_related_name": "%(app_label)s_%(model_name)s",
                "permissions": [
                    ("manage_roles_ansibledistribution", "Can manage roles on distributions")
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="ansiblerepository",
            options={
                "default_related_name": "%(app_label)s_%(model_name)s",
                "permissions": [
                    (
                        "rebuild_metadata_ansiblerepository",
                        "Can rebuild metadata on the repository",
                    ),
                    ("repair_ansiblerepository", "Can repair the repository"),
                    ("sign_ansiblerepository", "Can sign content on the repository"),
                    ("sync_ansiblerepository", "Can start a sync task on the repository"),
                    ("manage_roles_ansiblerepository", "Can manage roles on repositories"),
                    ("modify_ansible_repo_content", "Can modify repository content"),
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="collectionremote",
            options={
                "default_related_name": "%(app_label)s_%(model_name)s",
                "permissions": (
                    ("manage_roles_collectionremote", "Can manage roles on collection remotes"),
                ),
            },
        ),
        migrations.AlterModelOptions(
            name="gitremote",
            options={
                "default_related_name": "%(app_label)s_%(model_name)s",
                "permissions": [("manage_roles_gitremote", "Can manage roles on git remotes")],
            },
        ),
        migrations.AlterModelOptions(
            name="roleremote",
            options={
                "default_related_name": "%(app_label)s_%(model_name)s",
                "permissions": [("manage_roles_roleremote", "Can manage roles on role remotes")],
            },
        ),
        migrations.AlterField(
            model_name="ansibledistribution",
            name="distribution_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="core.distribution",
            ),
        ),
        migrations.AlterField(
            model_name="ansiblerepository",
            name="repository_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="core.repository",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="pulp_id",
            field=models.UUIDField(
                default=pulpcore.app.models.base.pulp_uuid,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="collectionremote",
            name="remote_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="core.remote",
            ),
        ),
        migrations.AlterField(
            model_name="collectionversion",
            name="content_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="core.content",
            ),
        ),
        migrations.AlterField(
            model_name="collectionversion",
            name="tags",
            field=models.ManyToManyField(editable=False, to="ansible.tag"),
        ),
        migrations.CreateModel(
            name="CollectionVersionMark",
            fields=[
                (
                    "content_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.content",
                    ),
                ),
                ("value", models.SlugField()),
                (
                    "marked_collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marks",
                        to="ansible.collectionversion",
                    ),
                ),
            ],
            options={
                "default_related_name": "%(app_label)s_%(model_name)s",
                "unique_together": {("value", "marked_collection")},
            },
            bases=("core.content",),
        ),
        migrations.AlterField(
            model_name="collectionversionsignature",
            name="content_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="core.content",
            ),
        ),
        migrations.CreateModel(
            name="CrossRepositoryCollectionVersionIndex",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_deprecated", models.BooleanField()),
                ("is_signed", models.BooleanField()),
                ("is_highest", models.BooleanField()),
                (
                    "collection_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ansible.collectionversion"
                    ),
                ),
                (
                    "namespace_metadata",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ansible.ansiblenamespacemetadata",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ansible.ansiblerepository"
                    ),
                ),
                (
                    "repository_version",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.repositoryversion",
                    ),
                ),
            ],
            options={
                "default_related_name": "%(app_label)s_%(model_name)s",
                "unique_together": {("repository", "repository_version", "collection_version")},
            },
        ),
        migrations.CreateModel(
            name="CollectionDownloadCount",
            fields=[
                (
                    "pulp_id",
                    models.UUIDField(
                        default=pulpcore.app.models.base.pulp_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("pulp_created", models.DateTimeField(auto_now_add=True)),
                ("pulp_last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("namespace", models.CharField(db_index=True, editable=False, max_length=64)),
                ("name", models.CharField(db_index=True, editable=False, max_length=64)),
                ("download_count", models.BigIntegerField(default=0)),
            ],
            options={
                "unique_together": {("namespace", "name")},
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.AlterField(
            model_name="downloadlog",
            name="pulp_id",
            field=models.UUIDField(
                default=pulpcore.app.models.base.pulp_uuid,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="gitremote",
            name="remote_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="core.remote",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="content_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="core.content",
            ),
        ),
        migrations.AlterField(
            model_name="roleremote",
            name="remote_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="core.remote",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="pulp_id",
            field=models.UUIDField(
                default=pulpcore.app.models.base.pulp_uuid,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AddField(
            model_name="collectionversion",
            name="version_major",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="collectionversion",
            name="version_minor",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="collectionversion",
            name="version_patch",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="collectionversion",
            name="version_prerelease",
            field=models.CharField(default="", max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ansiblecollectiondeprecated",
            name="content_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="core.content",
            ),
        ),
    ]
