# Generated by Django 2.1.7 on 2019-03-19 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsibleRemote',
            fields=[
                ('remote_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Remote')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.remote',),
        ),
        migrations.CreateModel(
            name='AnsibleRole',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Content')),
                ('namespace', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
            ],
            bases=('core.content',),
        ),
        migrations.CreateModel(
            name='AnsibleRoleVersion',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Content')),
                ('version', models.CharField(max_length=128)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='ansible.AnsibleRole')),
            ],
            bases=('core.content',),
        ),
        migrations.AlterUniqueTogether(
            name='ansiblerole',
            unique_together={('namespace', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='ansibleroleversion',
            unique_together={('version', 'role')},
        ),
    ]
