# Generated by Django 2.1.2 on 2018-10-05 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pulp_app', '0002_auto_20181005_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsibleRemote',
            fields=[
                ('remote_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pulp_app.Remote')),
            ],
            options={
                'abstract': False,
            },
            bases=('pulp_app.remote',),
        ),
        migrations.CreateModel(
            name='AnsibleRole',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pulp_app.Content')),
                ('namespace', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
            ],
            bases=('pulp_app.content',),
        ),
        migrations.CreateModel(
            name='AnsibleRoleVersion',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pulp_app.Content')),
                ('version', models.CharField(max_length=128)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='pulp_ansible.AnsibleRole')),
            ],
            bases=('pulp_app.content',),
        ),
        migrations.AlterUniqueTogether(
            name='ansiblerole',
            unique_together={('namespace', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='ansibleroleversion',
            unique_together={('version', 'role')},
        ),
    ]
