# Generated by Django 2.2.4 on 2019-08-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansible', '0003_add_tags_and_collectionversion_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionversion',
            name='name',
            field=models.CharField(editable=False, max_length=64),
        ),
    ]
