# Generated by Django 2.2.16 on 2020-09-18 20:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ansible', '0023_alter_requirements_file_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansiblerepository',
            name='extra_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, editable=False),
        ),
    ]
