# Generated by Django 2.2.16 on 2020-10-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansible', '0024_remove_collectionversion_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionversion',
            name='version_index',
            field=models.IntegerField(default=-1),
        ),
    ]
