# Generated by Django 2.2.16 on 2020-10-07 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_fips_checksums'),
        ('ansible', '0024_remove_collectionversion_certification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='deprecated',
        ),
        migrations.CreateModel(
            name='CollectionRepoMetadata',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='ansible_collectionrepometadata', serialize=False, to='core.Content')),
                ('namespace', models.CharField(editable=False, max_length=64)),
                ('name', models.CharField(editable=False, max_length=64)),
                ('deprecated', models.BooleanField(default=False)),
                ('collection', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='repometadata', to='ansible.Collection')),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
                'unique_together': {('name', 'namespace', 'deprecated')},
            },
            bases=('core.content',),
        ),
    ]
