# Generated by Django 2.2.17 on 2020-12-10 15:04
import json
import tarfile
import django.contrib.postgres.fields.jsonb
from django.db import migrations

from pulp_ansible.app.tasks.utils import get_file_obj_from_tarball


def set_manifest_and_files_json(apps, schema_editor):
    CollectionVersion = apps.get_model("ansible", "CollectionVersion")
    for collection_version in CollectionVersion.objects.all():
        artifact = collection_version.contentartifact_set.get().artifact
        with artifact.file.open() as artifact_file, tarfile.open(fileobj=artifact_file, mode="r") as tar:
            collection_version.manifest = json.load(
                get_file_obj_from_tarball(tar, "MANIFEST.json", artifact.file.name)
            )
            collection_version.files = json.load(get_file_obj_from_tarball(tar, "FILES.json", artifact.file.name))
            collection_version.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ansible', '0028_collectionversion_namespace_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionversion',
            name='files',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='collectionversion',
            name='manifest',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, editable=False),
        ),
        migrations.RunPython(code=set_manifest_and_files_json,
                             reverse_code=migrations.RunPython.noop)
    ]
