# Generated by Django 2.2.18 on 2021-02-08 20:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ansible', '0031_ansiblerepository_last_synced_metadata_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionversion',
            name='execution_environment',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, editable=False),
        ),
    ]
