# Generated by Django 2.2.19 on 2021-04-06 18:19

from django.db import connection, migrations, models, transaction
import django.db.models.deletion


pks_to_delete = []


def migrate_data_from_old_master_model_to_new_master_model(apps, schema_editor):
    AnsibleDistribution = apps.get_model('ansible', 'AnsibleDistribution')
    CoreDistribution = apps.get_model('core', 'Distribution')
    for old_ansible_distribution in AnsibleDistribution.objects.all():
        with transaction.atomic():
            new_master_model_entry = CoreDistribution(
                pulp_id=old_ansible_distribution.pulp_id,
                pulp_created=old_ansible_distribution.pulp_created,
                pulp_last_updated=old_ansible_distribution.pulp_last_updated,
                pulp_type=old_ansible_distribution.pulp_type,
                name=old_ansible_distribution.name,
                base_path=old_ansible_distribution.base_path,
                content_guard=old_ansible_distribution.content_guard,
                remote=old_ansible_distribution.remote,
                repository_version=old_ansible_distribution.repository_version,
            )
            new_master_model_entry.save()
            old_ansible_distribution.distribution_ptr = new_master_model_entry
            old_ansible_distribution.save()
            pks_to_delete.append(old_ansible_distribution.pulp_id)


def delete_remaining_old_master_model_entries(apps, schema_editor):
    with connection.cursor() as cursor:
        for pk in pks_to_delete:
            cursor.execute("DELETE from core_basedistribution WHERE pulp_id = %s", [pk])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_add_new_distribution_mastermodel'),
        ('ansible', '0032_collectionremote_sync_dependencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansibledistribution',
            name='distribution_ptr',
            field=models.OneToOneField(auto_created=True, null=True, default=None,
                                       on_delete=django.db.models.deletion.CASCADE,
                                       parent_link=True, primary_key=False,
                                       related_name='ansible_ansibledistribution', serialize=False,
                                       to='core.Distribution'),
            preserve_default=False,
        ),
        migrations.RunPython(migrate_data_from_old_master_model_to_new_master_model),
        migrations.RemoveField(
            model_name='ansibledistribution',
            name='basedistribution_ptr',
        ),
        migrations.AlterField(
            model_name='ansibledistribution',
            name='distribution_ptr',
            field=models.OneToOneField(auto_created=True,
                                       on_delete=django.db.models.deletion.CASCADE,
                                       parent_link=True, primary_key=True,
                                       related_name='ansible_ansibledistribution', serialize=False,
                                       to='core.Distribution'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='ansibledistribution',
            name='repository_version',
        ),
        migrations.RemoveField(
            model_name='ansibledistribution',
            name='repository',
        ),
        migrations.RunPython(delete_remaining_old_master_model_entries),
    ]
