# Generated by Django 3.2.8 on 2021-10-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansible', '0037_gitremote'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionversion',
            name='scmref',
            field=models.CharField(blank=True, default='', editable=False, max_length=2000),
        ),
    ]
