# Generated by Django 3.2.8 on 2021-10-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansible', '0038_collectionversion_scmref'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectionversion',
            old_name='scmref',
            new_name='commit',
        ),
        migrations.AddField(
            model_name='collectionversion',
            name='is_role',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
