# Generated by Django 3.2.13 on 2022-05-25 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_taskschedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ansible', '0041_alter_collectionversion_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionDownloadLog',
            fields=[
                ('pulp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('ip', models.GenericIPAddressField()),
                ('org_id', models.CharField(max_length=64, null=True)),
                ('user_agent', models.TextField()),
                ('collection_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_logs', to='ansible.collectionversion')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_logs', to='core.repository')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='download_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
