# Generated by Django 3.2.13 on 2022-04-29 07:49

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ansible', '0041_alter_collectionversion_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionVersionDownload',
            fields=[
                ('pulp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('client', models.CharField(editable=False, max_length=64)),
                ('count', models.IntegerField(default=0)),
                ('collection_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='ansible.collectionversion')),
            ],
            options={
                'unique_together': {('collection_version', 'client')},
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
