# Generated by Django 3.2.14 on 2022-07-21 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansible', '0044_collectionversion_sha256_migrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionversion',
            name='sha256',
            field=models.CharField(db_index=True, max_length=64, null=False),
        ),
        migrations.AlterUniqueTogether(
            name='collectionversion',
            unique_together={('sha256',)},
        ),
    ]
