# Generated by Django 3.2.16 on 2023-01-13 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_pulp_labels'),
        ('ansible', '0046_add_fulltext_search_fix'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsibleNamespace',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='ansible_ansiblenamespace', serialize=False, to='core.content')),
                ('name', models.CharField(max_length=64)),
                ('company', models.CharField(blank=True, default='', max_length=64)),
                ('email', models.CharField(blank=True, default='', max_length=256)),
                ('description', models.CharField(blank=True, default='', max_length=256)),
                ('resources', models.TextField(blank=True, default='')),
                ('links', models.JSONField(default=dict)),
                ('avatar_sha256', models.CharField(max_length=64, null=True)),
                ('metadata_sha256', models.CharField(db_index=True, max_length=64)),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
                'unique_together': {('metadata_sha256',)},
            },
            bases=('core.content',),
        ),
    ]
