# Generated by Django 3.2.18 on 2023-02-23 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ansible', '0047_ansible_namespace'),
        ('ansible', '0047_collectionversionmark'),
    ]

    operations = [
    ]
