# Generated by Django 3.2.17 on 2023-02-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansible', '0047_add_repo_cv_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossRepositoryCollectionVersionIndexView',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('distribution_name', models.CharField(max_length=255)),
                ('dist_id', models.UUIDField()),
                ('reponame', models.CharField(max_length=255)),
                ('repo_id', models.UUIDField()),
                ('namespace', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('is_deprecated', models.BooleanField()),
                ('is_signed', models.BooleanField()),
                ('cv_created_at', models.DateTimeField()),
                ('cv_updated_at', models.DateTimeField()),
                ('cv_requires_ansible', models.CharField(null=True, max_length=255)),
                ('cv_dependencies', models.JSONField()),
            ],
            options={
                'db_table': 'ansible_cross_repository_collection_versions_view',
                'managed': False,
            },
        ),
    ]
