# Generated by Django 4.2.6 on 2023-10-23 14:56

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import pulpcore.app.models.base
import pulpcore.app.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0112_alter_upstreampulp_options"),
        ("ansible", "0055_alter_collectionversion_version_alter_role_version"),
    ]

    operations = [
        migrations.CreateModel(
            name="SigstoreSigningService",
            fields=[
                (
                    "pulp_id",
                    models.UUIDField(
                        default=pulpcore.app.models.base.pulp_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("pulp_created", models.DateTimeField(auto_now_add=True)),
                ("pulp_last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(db_index=True, max_length=64, unique=True)),
                ("rekor_url", models.TextField(default="https://rekor.sigstore.dev")),
                ("rekor_root_pubkey", models.TextField(null=True)),
                ("fulcio_url", models.TextField(default="https://fulcio.sigstore.dev")),
                (
                    "tuf_url",
                    models.TextField(
                        default="https://sigstore-tuf-root.storage.googleapis.com/", null=True
                    ),
                ),
                ("oidc_issuer", models.TextField(default="https://oauth2.sigstore.dev/auth")),
                ("oidc_client_secret", pulpcore.app.models.fields.EncryptedTextField(null=True)),
                ("ctfe_pubkey", models.TextField(null=True)),
            ],
            options={
                "default_related_name": "%(app_label)s_%(model_name)s",
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="SigstoreVerifyingService",
            fields=[
                (
                    "pulp_id",
                    models.UUIDField(
                        default=pulpcore.app.models.base.pulp_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("pulp_created", models.DateTimeField(auto_now_add=True)),
                ("pulp_last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(db_index=True, max_length=64, unique=True)),
                ("rekor_url", models.TextField(default="https://rekor.sigstore.dev")),
                ("rekor_root_pubkey", models.TextField(null=True)),
                (
                    "tuf_url",
                    models.TextField(default="https://sigstore-tuf-root.storage.googleapis.com/"),
                ),
                ("certificate_chain", models.TextField(null=True)),
                ("expected_oidc_issuer", models.TextField()),
                ("expected_identity", models.TextField()),
                ("verify_offline", models.BooleanField(default=False, null=True)),
            ],
            options={
                "default_related_name": "%(app_label)s_%(model_name)s",
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name="ansiblerepository",
            options={
                "default_related_name": "%(app_label)s_%(model_name)s",
                "permissions": [
                    (
                        "rebuild_metadata_ansiblerepository",
                        "Can rebuild metadata on the repository",
                    ),
                    ("repair_ansiblerepository", "Can repair the repository"),
                    ("sign_ansiblerepository", "Can sign content on the repository"),
                    (
                        "sigstore_sign_ansiblerepository",
                        "Can sign content on the repository with Sigstore",
                    ),
                    ("sync_ansiblerepository", "Can start a sync task on the repository"),
                    ("manage_roles_ansiblerepository", "Can manage roles on repositories"),
                    ("modify_ansible_repo_content", "Can modify repository content"),
                ],
            },
        ),
        migrations.AddField(
            model_name="ansiblerepository",
            name="sigstore_verifying_service",
            field=models.ManyToManyField(
                blank=True,
                related_name="ansible_repositories",
                to="ansible.sigstoreverifyingservice",
            ),
        ),
        migrations.CreateModel(
            name="CollectionVersionSigstoreSignature",
            fields=[
                (
                    "content_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.content",
                    ),
                ),
                ("sigstore_bundle", models.JSONField(null=True)),
                (
                    "sigstore_bundle_sha256_hash",
                    models.CharField(db_index=True, max_length=64, null=True, unique=True),
                ),
                (
                    "signed_collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sigstore_signatures",
                        to="ansible.collectionversion",
                    ),
                ),
                (
                    "sigstore_signing_service",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sigstore_signatures",
                        to="ansible.sigstoresigningservice",
                    ),
                ),
            ],
            options={
                "default_related_name": "%(app_label)s_%(model_name)s",
                "unique_together": {("sigstore_bundle_sha256_hash", "signed_collection")},
            },
            bases=("core.content",),
        ),
    ]
