# Generated by Django 5.2.15 on 2026-07-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ansible", "0065_collectionversion_ansible_col_namespa_ea6f75_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionremote",
            name="sync_highest_versions",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
