#!/usr/bin/env sh

# WARNING: DO NOT EDIT!
#
# This file was generated by plugin_template, and is managed by bootstrap.py. Please use
# bootstrap.py to update this file.
#
# For more info visit https://github.com/pulp/plugin_template

set -v

export PRE_BEFORE_SCRIPT=$TRAVIS_BUILD_DIR/.travis/pre_before_script.sh
export POST_BEFORE_SCRIPT=$TRAVIS_BUILD_DIR/.travis/post_before_script.sh

if [ -f $PRE_BEFORE_SCRIPT ]; then
    $PRE_BEFORE_SCRIPT
fi


mkdir -p ~/.config/pulp_smash
curl -o ~/.config/pulp_smash/settings.json https://raw.githubusercontent.com/pulp/pulpcore/d34076e6f9ac47e0f4074f35fa1f746ae7fe6962/.travis/pulp-smash-config.json


if [ -f $POST_BEFORE_SCRIPT ]; then
    $POST_BEFORE_SCRIPT
fi
